### ISSUE TITLE
`ml-ulex` and `ml-yacc` not found while running `cmb-make`

### ISSUE THREAD

**Issue by dram** [smlnj/legacy#255]
### Version

110.99.3 (Latest)

### Operating System

- [ ] Any
- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Debian GNU/Linux 11 (bullseye)

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [X] x86-64 (64-bit)
- [ ] Other

### System Component

Installation

### Severity

Minor

### Description

While trying to build `main` branch of smlnj following steps described in `README.md`, following error occurred during `cmb-make`:

```
[plugin $/mllex-tool.cm loaded successfully]
["ml-ulex" --ml-lex-mode "lex/ml.lex"]
sh: 1: ml-ulex: not found
/home/debian/code/smlnj/legacy/base/compiler/Parse/parser.cm:42.2-42.12 Error: tool "ULex-ML-Lex" failed: "ml-ulex" --ml-lex-mode "lex/ml.lex"
["ml-ulex" --ml-lex-mode "lex/sml.lex"]
sh: 1: ml-ulex: not found
/home/debian/code/smlnj/legacy/base/compiler/Parse/parser.cm:43.2-43.13 Error: tool "ULex-ML-Lex" failed: "ml-ulex" --ml-lex-mode "lex/sml.lex"
[attempting to load plugin $/mlyacc-tool.cm]
[library $/mlyacc-tool.cm is stable]
[plugin $/mlyacc-tool.cm loaded successfully]
["ml-yacc"  "parse/ml.grm"]
sh: 1: ml-yacc: not found
/home/debian/code/smlnj/legacy/base/compiler/Parse/parser.cm:44.2-44.14 Error: tool "ML-Yacc" failed: "ml-yacc"  "parse/ml.grm"
["ml-yacc"  "parse/sml.grm"]
sh: 1: ml-yacc: not found
/home/debian/code/smlnj/legacy/base/compiler/Parse/parser.cm:45.2-45.15 Error: tool "ML-Yacc" failed: "ml-yacc"  "parse/sml.grm"
```

This problem can be solved by overriding `PATH` environment while running `cmb-make`, i.e.:

```
PATH=$PWD/../../bin:$PATH ./cmb-make
```

### Steps to Reproduce

1. run `which ml-ulex ml-yacc` to make sure there are no `ml-ulex` and `ml-yacc` installed
2. git clone https://github.com/smlnj/legacy.git
3. cd legacy
4. config/install.sh
5. cd base/system
6. ./cmb-make ../../bin/sml

### Email address

dram dot wang at gmail dot com

**Comment by JohnReppy** [comment]
Our expectation is that if you are recompiling the system from source, then you have the tools in your path.  I guess that we could add the directory containing the sml command (when specified) to the end of the user's path.

**Comment by JohnReppy** [comment]
For now, I have updated the README file to explain the path issue (I'll do the same for the development branch).
