### ISSUE TITLE
All downloads seem to be broken?

### ISSUE THREAD

**Issue by msridhar** [smlnj/legacy#257]
### Version

110.99.3 (Latest)

### Operating System

- [ ] Any
- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other Unix

### OS Version

Any version

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [X] x86-64 (64-bit)
- [ ] Other

### System Component

Installation

### Severity

Critical

### Description

All downloads of legacy SML/NJ versions for Windows seem to be broken.  E.g., this URL does not work:

http://smlnj.cs.uchicago.edu/dist/working/110.99.3/smlnj-110.99.3.msi

This worked a couple of weeks ago for me so I'm guessing it's due to a more recent change.

Sorry if this is the wrong place to report this problem.  I teach SML in my class so it'd be great if this could be fixed soon.

### Steps to Reproduce

Try to follow the link, and you get a 404

### Email address

manu@cs.ucr.edu

**Comment by JohnReppy** [comment]
In the middle of migrating the master copy of the web site to GitHub and my scripts for pushing the web pages to the server encountered a permission issue.  The missing files are being restored; should be all there in an hour or so.

**Comment by msridhar** [comment]
Thank you for the fix!
