### ISSUE TITLE
Version 110.99.4 does not launch on Ventura 13.5.1

### ISSUE THREAD

**Issue by danielzkng** [smlnj/legacy#281]
### Version

110.99.4 (Latest)

### Operating System

- [ ] Any
- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

13.5.1

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [X] x86-64 (64-bit)
- [ ] Other

### System Component

Core system

### Severity

Major

### Description

When I tried to install a fresh version of SML/NJ 110.99.4, I was given an "installation failed" screen at the end of the installer. Most of the directories appear to have been written to `/usr/local/smlnj`, and the `/usr/local/smlnj/bin/sml` executable exists, but when this executable is run, it outputs "sml: unable to determine architecture/operating system" and then exits.

### Expected Behavior

Expected SML/NJ 110.99.4 to install and start normally, since 110.99.4 is supposed to support MacOS up to MacOS 14 Sonoma.

### Steps to Reproduce

1. Delete any existing installations of SML/NJ from the `/usr/local` directory on MacOS Ventura 13.5.1
2. Run the SML/NJ installer for 110.99.4.
3. Attempt to run the `/usr/local/smlnj/bin/sml` executable.

### Additional Information

I would be happy to provide any other debugging outputs you need, but am not sure what else is useful to provide at the moment.

### Email address

danielzkng0 (at) gmail [dot] com

**Comment by JohnReppy** [comment]
Could you please attach the installer log?  You can get the log window by ⌘L when you first launch the installer.  Once the installation has run (and failed), you should be able to save it to a file.  Thanks.

**Comment by danielzkng** [comment]
I've attached the installer log.

[Installer Log 28-Aug-2023.txt](https://github.com/smlnj/legacy/files/12456345/Installer.Log.28-Aug-2023.txt)

**Comment by JohnReppy** [comment]
It looks like you might have downloaded the 32-bit installer (smlnj-x86-110.99.4.pkg) instead of the 64-bit one ([smlnj-amd64-110.99.4.pkg](http://smlnj.cs.uchicago.edu/dist/working/110.99.4/smlnj-amd64-110.99.4.pkg).

**Comment by danielzkng** [comment]
This solved my problem, thank you!
