### ISSUE TITLE
Get "fgrep is obsolescent" when run 'sml' on Fedora

### ISSUE THREAD

**Issue by rgizz** [smlnj/legacy#286]
### Version

110.99.4 (Latest)

### Operating System

- [ ] Any
- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Fedora 38

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [X] x86-64 (64-bit)
- [ ] Other

### System Component

Command-line tool

### Severity

Cosmetic

### Description

When I type 'sml' on the command line, I get a warning that "fgrep is obsolescent" before the Smlnj repl launches. It works fine, so this is simply cosmetic. 

### Transcript

$ sml
fgrep: warning: fgrep is obsolescent; using grep -F
Standard ML of New Jersey (64-bit) v110.99.4 [built: Tue Nov 14 10:09:53 2023]
- 

### Expected Behavior

$ sml
Standard ML of New Jersey (64-bit) v110.99.4 [built: Tue Nov 14 10:09:53 2023]
- 

### Steps to Reproduce

Just launch repl by typing 'sml'

### Additional Information

It seems to arise from two uses of fgrep in bin/.run-sml, on lines 168 and 172. If I replace 'fgrep' with 'grep -F' on those two lines the warning goes away. 

### Email address

gztown2216@yahoo.com

**Comment by JohnReppy** [comment]
This issue has already been addressed (1346e9655842a9b7597bf4176ba27962384902b0) and will be fixed in 110.99.5.
