### ISSUE TITLE
Starting SML/NJ on Windows produces unsightly REM lines

### ISSUE THREAD

**Issue by kcrary** [smlnj/legacy#294]
### Version

110.99.4 (Latest)

### Operating System

- [ ] Any
- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other Unix

### OS Version

Windows 10

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [X] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Core system

### Severity

Cosmetic

### Description

When starting SML/NJ on Windows, you see a bunch of comment lines:

The solution is to move the `@echo OFF` line in bin/sml.bat to the top.

### Transcript

```
Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. All rights reserved.

c:\crary>sml c:/crary/lib/sml/misc.sml

c:\crary>REM sml.bat 

c:\crary>REM

c:\crary>REM Copyright 2020 The Fellowship of SML/NJ (http://www.smlnj.org) 

c:\crary>REM All rights reserved. 

c:\crary>REM

c:\crary>REM The standard driver for SML/NJ under the new runtime system 

c:\crary>REM
Standard ML of New Jersey (32-bit) v110.99.3 [built: Thu Jul 28 00:45:02 2022]
```

**Comment by JohnReppy** [comment]
Made the suggested edit to the `sml.bat` file.  Fixed for 110.99.5.
