### ISSUE TITLE
Additional operations for the `MONO_HASH_TABLE` interface

### ISSUE THREAD

**Issue by Skyb0rg007** [smlnj/legacy#297]
### Description

The hash table in the SML/NJ library is missing some operations that would be useful.

    signature MONO_HASH_TABLE = sig
      (* ... *)
      (* Same as those in ORD_MAP *)
      val insertWith : ('a * 'a -> 'a) -> 'a hash_table -> Key.hash_key * 'a -> unit
      val findAndRemove : 'a hash_table -> Key.hash_key -> 'a option
    end

**Comment by JohnReppy** [comment]
These have been implemented for 110.99.5.  Also added the functions to the `HashTable` structure.
