### ISSUE TITLE
Incorrect printing of source code in error message

### ISSUE THREAD

**Issue by JohnReppy** [smlnj/legacy#298]
### Version

110.99.4 (Latest)

### Operating System

- [X] Any
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

- [X] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Core system

### Severity

Minor

### Description

The compiler prints `;` as `,` when printing the syntax of a term as part of an error message.

### Transcript

```
Standard ML of New Jersey (64-bit) v110.99.4 [built: Tue Aug 01 16:07:38 2023]
- if false then (1;2) else (3,4);
stdIn:1.2-1.32 Error: types of if branches do not agree [overload - bad instantiation]
  then branch: 'Z[INT]
  else branch: 'Y[INT] * 'X[INT]
  in expression:
    if false then (1, 2) else (3,4)
- 
```

### Expected Behavior

The source term should be printed as

```
    if false then (1; 2) else (3,4)
```

### Steps to Reproduce

See transcript.

### Email address

jhr@cs.uchicago.edu

**Comment by dmacqueen** [comment]
In function ppExp' in ElabData/syntax/ppabsyn.sml, string "," is replaced by ";".
