### ISSUE TITLE
`Random.randRange` when low = hi

### ISSUE THREAD

**Issue by dlicata335** [smlnj/legacy#313]
### Version

110.99.4

### Operating System

- [ ] Any
- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Catalina

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

SML/NJ Library

### Severity

Minor

### Description

I think the behavior of Random.randRange has changed in the past year (since I last used a homework that suddenly had a bug), and is inconsistent with the documentation.  The documentation says "val randRange : (int * int) -> rand -> int
randRange (lo, hi) rand generates a random number in the [lo..hi]. This function will raise the [Fail](https://standardml.org/Basis/general.html#SIG:GENERAL.Fail:EXN) exception if hi < lo."  This suggests one should be able to call it with low = hi (and necessarily get low=hi as the output).  However, 

 Random.randRange (1,1) (Random.rand(1,2)); 

raises Div.  

### Steps to Reproduce

 Random.randRange (1,1) (Random.rand(1,2)); 

### Email address

dlicata@wesleyan.edu

**Comment by JohnReppy** [comment]
FYI the `Random` module was rewritten to use the Mersenne Twister algorithm in release [110.99.4](http://smlnj.org/dist/working/110.99.4/110.99.4-README.html) to address issue #256.

**Comment by JohnReppy** [comment]
There was a missing `+ 1` in the computation of the range.  Fixed for 110.99.6.
