### ISSUE TITLE
`TimeLimit.timeLimit` immediately throws exception on Windows

### ISSUE THREAD

**Issue by MartinAskestad** [smlnj/legacy#320]
### Version

110.99.5 (Latest)

### Operating System

- [ ] Any
- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other Unix

### OS Version

Windows 11

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [x] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

SML/NJ Library

### Severity

Minor

### Description

In the Repl when running `TimeLimit.timeLimit (Time.fromSeconds 60) calculation ()` the TimeOut exception is thrown immediately. But by running the code once more, it behaves as expected. This appears to only occur on Windows, if running on Linux I can't reproduce the error.

### Expected Behavior

The exception should not be thrown if calculations complete withing the time limit.

### Steps to Reproduce

Run a functon wrapped in the timeLimit function in the Repl on Windows.
`TimeLimit.timeLimit (Time.fromSeconds 60) calculation ()`

### Email address

m at rtin dot nu

**Comment by JohnReppy** [comment]
I checked **macOS** and it also appears free of the error, so I suspect that it is **Windows** specific.

**Comment by Skyb0rg007** [comment]
I can confirm that this bug exists on Windows. Are signals even implemented on Windows? (looking at [win32-signal.c](https://github.com/smlnj/legacy/blob/main/base/runtime/mach-dep/win32-signal.c) makes it seem like it isn't)

**Comment by JohnReppy** [comment]
I believe that there is support for SIGALRM (see [win32=timers.c](https://github.com/smlnj/legacy/blob/main/base/runtime/mach-dep/win32-timers.c)) that is implemented using a separate thread.

**Comment by JohnReppy** [comment]
Fixed for 110.99.6
