### ISSUE TITLE
Dynamic Array primitive type

### ISSUE THREAD

**Issue by Skyb0rg007** [smlnj/legacy#326]
### Description

The current internal representation of Vector and Array uses two pointers: the object contains the header and length along with a pointer to the actual objects in memory.
This enables an efficient implementation of dynamically resizable arrays, where the block of memory that stores the data items can be resized as necessary.

By making this a primitive type, it potentially simplifies programs that generate an unknown number of outputs as they can now use the dynamic array to store items instead of a reference to a list that needs to be reversed.

**Comment by JohnReppy** [comment]
Such an improvement is planned for the development branch, but I don't think that it will be back ported to the legacy repository.
