### ISSUE TITLE
Real.fromString broken in 110.99.5 and 110.99.6

### ISSUE THREAD

**Issue by dlicata335** [smlnj/legacy#328]
### Version

110.99.6 (Latest)

### Operating System

- [ ] Any
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [ ] PowerPC
- [ ] Sparc
- [ ] x86 (32-bit)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Basis Library

### Severity

Major

### Description

Real.fromString seems to be ignoring/misinterpreting the decimal point.  It worked last semester on 110.99.4 but is broken for some students this semester on 110.99.5, and also on 110.99.6.  

### Steps to Reproduce

Real.fromString ("1.11");
val it = SOME 1 : real option

- Real.fromString ("123.45");
val it = SOME 123 : real option

Real.fromString (".11");
val it = SOME 1100 : real option

Real.fromString ("0.11");
val it = SOME 0 : real option

### Email address

dlicata@wesleyan.edu

**Comment by JohnReppy** [comment]
Not quite sure how this slipped through, but I've pushed a fix.  Since it is a pretty severe bug, I am going to make a patch release (110.99.6.1) with the fix.

**Comment by dlicata335** [comment]
thanks!

**Comment by JohnReppy** [comment]
The updated code and binfiles for 110.99.6.1 are available at https://smlnj.org/dist/working/110.99.6.1.  I will announce it once I've got the installers for macOS and Windows built.

**Comment by dlicata335** [comment]
Working better, but something is still going wrong with trailing 0's.  
``
Standard ML of New Jersey [Version 110.99.6.1; 64-bit; October 25, 2024]
- Real.fromString ("1.0");
[autoloading]
[library $SMLNJ-BASIS/basis.cm is stable]
[library $SMLNJ-BASIS/(basis.cm):basis-common.cm is stable]
[autoloading done]
val it = SOME 10 : real option
- Real.fromString ("1.01");
val it = SOME 1.01 : real option
``

**Comment by JohnReppy** [comment]
Sorry for being slow to respond.  Somehow, I missed the notification from GitHub.  I have a fix for the trailing zero issue, so I can put out another patch release if that would be useful.

**Comment by dlicata335** [comment]
Thanks!  I already put a workaround in the homework that uses this, so no urgent need to patch for me.
