### ISSUE TITLE
Unable to interrupt execution by using SIGINT

### ISSUE THREAD

**Issue by JohnReppy** [smlnj/legacy#68]
### Version

110.99.2

### Operating System

- [ ] All
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [X] Other Unix

### Component

Core system

### Severity

Major

### Description of the problem

In smlnj v110.99.2, I am not able to interrupt the execution of an expression by sending SIGINT to smlnj.
For example, if I run an infinite loop `while true do ();`, I am not able to stop it by pressing CTRL-C.
Older versions of smlnj do not seem to have this problem. In smlnj v110.79, I am able to stop the infinite loop using CTRL-C:

Standard ML of New Jersey v110.79 [built: Sun Oct 27 08:29:41 2019]
- while true do ();

Interrupt
-

#### Original smlnj-gforge bug number 311

Submitted  on 2022-50-19 at 23:5000

#### comment by @JohnReppy on 2022-20-20 09:2000 +000 UTC

I was unable to reproduce this bug (macOS/arm64)  Since the report does not provide any contact info and does not specify the version of Unix/architecture, I'm not able to do further testing or ask for additional information.

**Comment by JohnReppy** [comment]
I have also verified that this issue is not a problem on Linux in the 110.99.3.

**Comment by JohnReppy** [comment]
Based on email from the original submitter, the problem is actually with the way that the signal-handling state is being maintained across `exportML`.  If a signal is set to be ignored in the environment when `exportML` is called, that behavior is preserved when the program is restarted.  We need to figure out a precise description of signal semantics (and how it interacts with `exportML` and `exportFn`) and correct the implementation.

**Comment by JohnReppy** [comment]
Fixed this problem by delaying the setup of the signal handler state until after the heap image is loaded.   This change means that the signals that are ignored when the image is created, but not when the image is run, will not be ignored.

**Comment by cwfoo** [comment]
I am the original submitter of this bug report. For future reference, here is an excerpt from the mailing list thread where I provided additional information about this bug:

> SML/NJ version: v110.99.2
> OS: Ubuntu 20.04 (Linux 5.13.0)
> 
> If I run an infinite loop `while true do ();`, I am not able to stop it
> by pressing CTRL-C. According to /proc/{pid}/status, SML/NJ is ignoring
> SIGINT:
> 
>     SigPnd:
>     SigBlk:
>     SigIgn: INT(2) QUIT(3)
>     SigCgt: FPE(8) SEGV(11) TERM(15)

> I did some tests and found that this problem only occurs when SML/NJ is
> built in relatively unusual environments where SIGINT is ignored
> (I happened to have installed smlnj via GNU Guix). I was able to
> reproduce the problem reliably in Ubuntu 20.04 by installing
> SML/NJ 110.99.2 using these steps:
> 
> ```
> $ wget 'http://smlnj.cs.uchicago.edu/dist/working/110.99.2/config.tgz'
> $ tar xvf config.tgz
> $ trap '' INT
> $ config/install.sh -default 64
> ```
> 
> The resulting sml executable will ignore SIGINT.

**Comment by JohnReppy** [comment]
Are you still experiencing the problem in 110.99.3?
