### ISSUE TITLE
Real.fromManExp does not return expected value if man = 0.0

### ISSUE THREAD

**Issue by JohnReppy** [smlnj/legacy#72]
### Version

110.99

### Operating System

- [X] All
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

Any

### Component

Basis Library

### Severity

Minor

### Description of the problem

For any integer `exp` the expression

  Real.fromManExp {man = 0.0, exp = exp}

does not return the expected value.  The Basis Library states "If man is +-0, the result is +-0."
https://smlfamily.github.io/Basis/real.html#SIG:REAL.fromManExp:VAL

With 110.85, the expression raises the exception Overflow.

With 110.99, evaluation of the expression does not terminate.

### Steps to Reproduce

Evaluate the expression

  Real.fromManExp {man = 0.0, exp = 0};

with versions 110.99 and 110.85.

### Email address

phil.clayton@veonix.com

#### Original smlnj-gforge bug number 316

Submitted via web form by Phil Clayton <phil.clayton@veonix.com> on 2022-02-05 at 13:0200

**Keywords:** reals

#### comment by @JohnReppy on 2022-12-05 15:1200 +000 UTC

Fixed for 110.99.3 and 2022.1

**Comment by pclayton** [comment]
I have found other values where `Real.fromManExp` has similar incorrect behaviour.  Did the fix for the issue reported here also fix the following cases?
```
Real.fromManExp {man = Real.posInf, exp = 0};  (* man = inf *)
Real.fromManExp {man = Real.posInf - Real.posInf, exp = 0};  (* man = nan *)
```
These cases produce the same result as above:

- With 110.85, the expressions raise the exception Overflow.
- With 110.99, evaluation of the expressions does not terminate.

In these cases, I would expect `Real.fromManExp` to return `man`.

**Comment by pclayton** [comment]
Great to see that SML/NJ has moved to Github!  I would have built the source to check for myself but I don't see build instructions so thought it would be quicker just to ask.

**Comment by pclayton** [comment]
Thanks for the build instructions in the README - the build worked fine.  Out of interest, is it necessary to always perform step 2 for subsequent builds?  For example, after pulling further commits from a remote branch, can I start at step 3?

**Comment by JohnReppy** [comment]
You can start at Step 3 (I've added a note to that effect to the README).
